version: '2'
services:
  web:
      build:
          context: ./
          dockerfile: web.docker
      volumes:
        - ./:/var/www
      ports:
        - "8080:80"
      links:
        - app
  app:
      build:
        context: ./
        dockerfile: app.docker
      volumes:
        - ./:/var/www
  database:
      image: mysql:5.6
      environment:
          - "MYSQL_ROOT_PASSWORD=secret"
          - "MYSQL_DATABASE=homestead"
      ports:
          - "3306:3306"
  cache:
      image: redis:3.0
      ports:
          - "6379:6379"
  mongo:
     image: mongo:latest
     container_name: mongo
     ports:
      - "27017:27017"
     volumes:
      - ./data:/data/db

